-- Migration: Add missing fields for frontend requirements
-- Generated by Helper Agent
-- Description: Adds 'display_name' to brands and 'is_new_product' to products.

BEGIN;

--------------------------------------------------------------------------------
-- 1. Table: brands (品牌)
-- Requirement: display_name (text)
--------------------------------------------------------------------------------

-- Add display_name if not exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'brands' AND column_name = 'display_name') THEN
        ALTER TABLE "brands" ADD COLUMN "display_name" TEXT;
        RAISE NOTICE 'Added column display_name to brands table';
    END IF;
END $$;

-- Populate display_name with existing nameEn or name if null
UPDATE "brands" 
SET "display_name" = COALESCE("name_en", "name") 
WHERE "display_name" IS NULL;


--------------------------------------------------------------------------------
-- 2. Table: products (產品)
-- Requirement: is_new_product (boolean, default false)
--------------------------------------------------------------------------------

-- Add is_new_product if not exists
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'is_new_product') THEN
        ALTER TABLE "products" ADD COLUMN "is_new_product" BOOLEAN DEFAULT false;
        RAISE NOTICE 'Added column is_new_product to products table';
    END IF;
END $$;

-- Note: Other requested fields were verified to exist:
-- brands: name, logo_url, colors
-- products: name, name_jp, description, price, original_price, currency, 
--           image_urls, source_url, available_start_date, available_end_date,
--           tags, is_limited_edition, status, metadata, created_at, updated_at

-- Create index for performance on is_new_product as it will be used for filtering
CREATE INDEX IF NOT EXISTS "idx_products_is_new_product" ON "products" ("is_new_product");

COMMIT;
